### ISSUE TITLE
Copy updates 

### ISSUE THREAD

**Issue by seattlehedgehog** [VotingVoices/chorus#102]
Jan proofed all results and has some good suggestions. Here is a compilation:

Voting Registration
Yes answer: 
Step X copy should read: Is your registration A-OK?
Please remove hyphens from “up-to-date” and spell it as “up to date” 

No answer:
Step X copy should read: Let’s do this—get registered!
Supporting copy should read: Take a minute to submit your registration and make sure you're vote ready.
Link should read: REGISTER NOW

Not Sure answer:
Supporting copy should read: Not sure whether you're registered? Take a minute now to find out.

Ballot Return: Mail
For CO, OR, WA, and Generic Mail answers:
Change supporting copy from “Check up on your deadline and rest easy. (And don't forget postage if your ballot envelope is not prepaid.)” to the following:
Don’t forget postage if your ballot envelope isn’t prepaid. [I made this change due to redundancy with Ballot Deadline supporting copy.]

For CO, OR, WA, and Generic Ballot Box answers:
Change supporting copy to read:
Drop off your ballot at a spot that’s close by and convenient

Special Accommodation: Polls
For the Yes answer supporting copy, please delete the second sentence that reads “It's easy to plan ahead!” [Made change because sentence is unnecessary and redundant.]

Transportation: Polls
The Carpool answer should read:
Step X: Carpool to the polls
Great plan. Even better, get the current address and directions before you go.
The Taxi answer supporting copy should read: Great plan. Even better, get the current address and directions before you go.

Miss Work: Polls
Change the answer to read as follows:
Step X: Are you eligible for paid time off to vote?

Sentiment:Polls
For the Meh answer, change the supporting copy to the following:
Feeling ambivalent? Now that your voting plans are taking shape, watch this and get inspired.

Please change all sentiment CTA links to: https://www.youtube.com/watch?v=WnOi4wapmNA&t=1s

**Comment by abrauninger** [comment]
Fixed in a4b126a.
