### ISSUE TITLE
Navbar styling issues

### ISSUE THREAD

**Issue by FalseLobster** [VotingVoices/chorus#46]
Right now the navigation links and the logo are misaligned in the navbar itself.

**Comment by FalseLobster** [comment]
Perhaps this should serve as a catchall for the other styling issues in the navbar? Namely, when collapsed to  mobile view, the hamburger menu opens with a transparent background making the links hard to read.  The navlinks are also not consistent with design.

**Comment by abrauninger** [comment]
I think most of these issues are fixed by c7252ea.  We should file separate issues for any remaining issues.  I think with the new flexbox layout for the header (and with About/Donate buttons) we'll need to figure out a hamburger-like solution for scaling down the header...
