### ISSUE TITLE
Copy change requests - compile

### ISSUE THREAD

**Issue by seattlehedgehog** [VotingVoices/chorus#55]
I compiled several copy change requests into one issue. Let me know if it would be better to separate them into separate issues. Thanks!

**Tool question copy**
Question #1 – remove “!” from yes reply

**Plan result copy**
Voter registration:
Yes reply – Change from “Let's do this: get registered!” to “Great--you're registered! Now take a quick look to make sure everything is up-to-date.”
Maybe reply should be: Header “Check your registration” Text – “Not sure whether you're registered? Take a minute to double-check and make sure you're vote ready.”
Ballot research:
No reply – Change “Now's the perfect time to research the candidates and issues you'll be voting for. Here's an app to help.” To “Now's the perfect time to research the candidates and issues you'll be voting for. The Ballot Ready app can help you make informed choices.”
Yes reply - Change “You're familiar with the candidates and issues--now put it all together using this handy app.” To “You're familiar with the candidates and issues.  The Ballot Ready app can help you make informed choices”
Sentiment:
Change CTA from “Your voice matters--take a look” to “See what happens When We All Vote
Polling place:
Change “Make it easy on yourself! Find your state's polling locations through the link below.” To “Make it easy on yourself! Find your polling location through the link below.”
Change “THIS WAY TO THE POLLS (SCROLL FOR YOUR STATE)!” to “THIS WAY TO THE POLLS”

Companions (until we can enable email invites):
Change “Let's keep each other accountable--voting's even better when we can do it together! Share your plans with the people in your life.” to ““Let's keep each other accountable--voting's even better when we can do it together!”
Change: “Invite your crowd to voteplan!” to “Invite your crowd to vote with you” – no CTA link

**Comment by abrauninger** [comment]
I've made these changes and pushed them to the live site.
