### ISSUE TITLE
Add Voter Guide Widget to plan results (all research replies)

### ISSUE THREAD

**Issue by seattlehedgehog** [VotingVoices/chorus#60]
Voter Guide Widget: <iframe style="background-color: transparent; border: none; overflow: hidden;" scrolling="no" src="https://www2.ballotready.org/widget/address_search" width="100%" height="200"><p>iframe not supported.</p></iframe>

**Comment by abrauninger** [comment]
@seattlehedgehog out of curiosity, does the Ballot Ready widget have a Spanish version that we can use in the future when we support Spanish?

**Comment by abrauninger** [comment]
Added in e8ce736.
