### ISSUE TITLE
"It's my M.O." string is both hard to read and hard to understand

### ISSUE THREAD

**Issue by abrauninger** [VotingVoices/chorus#62]
It doesn't render well in the scripty font, and I think a lot of people may not know what M.O. stands for.

**Comment by seattlehedgehog** [comment]
How does "I'm a voter" or "I vote!" sound/look?

**Comment by abrauninger** [comment]
How about "It's what I do"...?  (Maybe a little long)

"I'm a voter"/"I vote" don't seem quite right to me:

Remember your reason for voting!
I'm a voter

Remember your reason for voting!
I vote

Neither of those seem to really be the "reason for voting".  They just seem to be re-stating that they plan on voting.

**Comment by seattlehedgehog** [comment]
I like "It's what I do" if it fits. It's definitely less redundant under the heading.

**Comment by seattlehedgehog** [comment]
Civic Duty for the win!

**Comment by abrauninger** [comment]
Fixed in 5f72638.
