### ISSUE TITLE
Should we move the "Start Over" button on the Plan page?

### ISSUE THREAD

**Issue by abrauninger** [VotingVoices/chorus#63]
I demo'd the app to a friend of mine last night (on my iPhone).  I watched her go through the app, reading each survey question and answering it.  As soon as the got to the Plan page she clicked Start Over (without reading the plan at all), and then she was surprised that she was back at the beginning of the survey.

She explained later that when she saw the Plan page, she saw the scripty "VotePlan" logo and thought "that's hard to read and it's probably the logo" so she then looked down to the next thing that was visible, which was a button that seemed prominently placed, so she thought she should press it.

This experience is consistent with what I've seen from users in usability studies for other applications -- they tend not to read things, and sometimes they just click through in a hurry without thinking too carefully.

I think we might want to consider moving the "Start Over" button to the bottom of the Plan page to reduce accidental clicks.

**Comment by seattlehedgehog** [comment]
Yes! I did the same thing yesterday when proofing.

**Comment by abrauninger** [comment]
Fixed in 8cd186a.
